-- Drop Tables with CASCADE CONSTRAINTS to automatically remove any dependent objects
DROP TABLE miscellaneous_cost CASCADE CONSTRAINTS;
DROP TABLE ride CASCADE CONSTRAINTS;
DROP TABLE bike CASCADE CONSTRAINTS;
DROP TABLE location CASCADE CONSTRAINTS;
DROP TABLE address CASCADE CONSTRAINTS;
DROP TABLE id_detail CASCADE CONSTRAINTS;
DROP TABLE user_subs CASCADE CONSTRAINTS;
DROP TABLE users CASCADE CONSTRAINTS;
DROP TABLE bike_status CASCADE CONSTRAINTS;
DROP TABLE subs_plan CASCADE CONSTRAINTS;
DROP TABLE trans CASCADE CONSTRAINTS;
DROP TABLE trans_type CASCADE CONSTRAINTS;

-- Drop Sequences
DROP SEQUENCE miscellaneous_cost_seq;
DROP SEQUENCE ride_seq;
DROP SEQUENCE bike_seq;
DROP SEQUENCE location_seq;
DROP SEQUENCE address_seq;
DROP SEQUENCE id_detail_seq;
DROP SEQUENCE user_subs_seq;
DROP SEQUENCE user_seq;
DROP SEQUENCE bike_status_seq;
DROP SEQUENCE subs_plan_seq;
DROP SEQUENCE trans_seq;
DROP SEQUENCE trans_type_seq;
